resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: jaytest
      fileLocation: example-repo-local/setup/help # optional
      fileName: something.txt # optional
      fileDateTime: 19/12/19 # optional
 
 
pipelines:
  - name: pipelines_1
    steps:
      - name: REFILE_1
        type: Bash
        configuration:
          nodePool: default-dynamic-nodepool
          integrations:
            - name: jaytest
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - write-output "executing step..."
            - jfrog rt dl example-repo-local/package.json
