resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: jaytest 
      fileName: test.tar
      fileLocation: example-repo-local/
      
pipelines:
  - name: pipelines_1
    steps:
      - name: REFILE_1
        type: Bash
        configuration:
          nodePool: default-dynamic-nodepool
          integrations:
            - name: arti
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - echo "executing step..."
            - jfrog rt dl example-repo-local/package.json
            - tar -czvf test.tar package.json
